server:
  port: 8090
message:
  act: "heavyflood 503"
spring:  
  rabbitmq:
    host: 3.34.125.142
    port: 5672
    username: guest
    password: guest
  kafka:
    bootstrap-servers: http://54.180.80.239:9092    
