server:
  port: 8090
message:
  act: "heavyflood1235"
spring:  
  rabbitmq:
    host: 3.34.125.142
    port: 5672
    username: guest
    password: guest
  kafka:
    bootstrap-servers: http://3.34.125.142:9092    
