server:
  port: 8090
message:
  act: "heavyflood51"
management:  
  endpoints:
    web:
      exposure:
        include: "bus-refresh"  
spring:  
  rabbitmq:
    host: 52.79.157.106
    port: 5672
    username: guest
    password: guest  
