server:
  port: 20080
message:
  act: "09876"
---
spring:
  cloud:
    kubernetes:
      discovery:
        service-name: user
        primary-port-name: 9092
        enabled: true
        all-namespaces: true
        wait-cache-ready: false    
