management:
  endpoints:
    web:
      exposure:
        include: health,refresh,beans,httptrace,busrefresh
server:
  port: 9090

spring:
  application:
    name: config-server
  ## kafka config
  kafka:
    bootstrap-servers: 3.37.210.218:9092
  cloud:
    ## cloud bus config
    bus:
      enabled: true
#      refresh:
#        enabled: true
#      env:
#        enabled: true
    ## config server
    config:
      server:
        git:
          uri: git@github.com:heavyflood/gw-configs.git
          ignoreLocalSshSettings: true
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKAIBAAKCAgEA04VKLDFsVDrxKHpx3/bvA+kgg9NTXhgLWJD28BKi/0tpmu7I
            zsMpncuty55j9qx3JxUIsR6za1J4xBB7aYNCfVBeCLjN7+OL0u91VVgjZh1jKsCD
            UBtwDpfhOayK/iAmMBVNN++UHzRfMzs9Lan9T+fsVH84ViMn5q7hYsYsNpgg4Zm6
            wWutlOy7FWUIvEXbFHpCvehvSFVot3+p8hNeJF/pTUFJ9dznaM8l4PlsXGCub25q
            0/bBvBEqtn7LkOLbgrrDoW1dB6nMdMlxz/rW45OEnb1luArDO3dSDbq9lYGWma/0
            bsVqRXjHJ1zEisJbVFQIpUBgjHXxtKpg30keZtxgs4kp2GrGgJOOkS28kfC4bR0+
            Gi4GH7T0X9puXzobiCq4ubGQWw8bx+S+CJwvX+DFCAi19EW7elx/9FiwOv3GbeRS
            T1ZiQ5IEI6HsQE7Uty/b/m8h83w5s2GkoxhN31mFaBwZmQuCKy/Zr9MfugEvwH1G
            Ltcccf8630gnD8HXtKXrMMZauzZ7rSJb7tC6k8DLwU96CmUQMNCAbTD0TYIj+s/Y
            wNTFPRVCTV3+WzJZ75QIsXtBJAcIvrjbbP3v08Lm2Y1U2KMk0bKUhDQeacDpXnZn
            zkzbhQ66PKNU2CVeyz7vn22Cb39H72ipaPXi6DioEh5yka5pAbDUjRMHxaUCAwEA
            AQKCAgAWkeVtO8TUZAmxiQc3n7C3WRvYFSeTJbuoMqe2zDZKSXC2UH5q2ZZKOR6N
            WJRQEO0R5YOs6pq4e+9Y9G1Gv/PLTVULVzTaQQx9cIGznpkAX2hienJIjPTzCa/F
            qKyYGzQX813u9wh2H+98lvibM8VMznGAPqbzQgMS8VwpXv3+wVLY3792vheiiXQY
            /1PkSwvqbnVKsE+Xh02KLvwiUYC9HuLVFH9g1bZ3j4r6K4MthD94sm6BuZXIjIhj
            Orpb9mj31Rfk1LeVhr/DQm97gseFNwtyjXAaKEPWx4+g2Wk7V72LHqRVYYlKam3N
            vG9YYw69u83EXE8xDbDB12BI0xOEMpDCv8BJGu+rvA5nkNa23X1VoTfBeWD+z1nV
            q3tCxYdtN0suELArKzoixiI0fFFJRLj4QFlLWvIDIofKhEYZ2zL3OpBkLXdifw5F
            sZsNu/j8ld4hvMHXAAYc+CmUtxMh9H5sXeDGK2aDg8qWXwE3C0BbwV+gF9U1WZuT
            N4b9C4+iQJKYX2bGCdTUwDrMZzv6srrAQk9+XTkYt+RrxW+auQouiU5f7CFbY+Pb
            /RJX+eJmR/V2oSMnqtLhy2NyPy0uDZfesuY52T1tvZ9TAazF6o8fQOV+F9zLUOCA
            vlQLCQAbrw1IY5G4NciS6DOCASoignldsWqSBigjr9lioWVNQQKCAQEA8v6sEZVM
            Oms/ZQ9iRemDFFmkL++fNjWkv3/jo+nMlIcH/+Le2Q6oR0Ul6b3RHs8Ukd/SC5dg
            4nNX0MpXMoQNm/tV9+SWVSElyJ+FLElwyi6iU0RLzHD2iy0LV4vozRFBEl807bGF
            udeA5FO+cNRWNH1lseWF6W9ove7WcRmb5reQ1iIVmQjjWvgZ82MgxSS/hzzVxi8y
            XYcflQc02ILGhE7mNTR5LW4VXbbV48ArPT8HFOHYaRwa5XwD1F7R/ltfcdcpQWjR
            GEYHhoH04GaT6ldTjd9LdKMOf/2hlru4uYyYyBQO7NW+COll1oSP80FkChUVFGvT
            8ToksvyNLhwpEQKCAQEA3tdiDaKln5Ryy6ZnfiB1UbpycEaoUgk3QgPziyh+joJ/
            s6AHJXK7HN4jKQ31bgJWJNLxxryM3OFWLgg8icKrC+F7XkHEENQsFZU0/wkB/+sR
            NMqrrx3xRMSTTyfjTrhaM131hbYonlXiVKvmRSIOvfctcmf24wMO76CRo/oQ4mK8
            myYXswsjEJmzlFHGnNT694A9m/i1FEIWI2FdLavpTBE01n/F+DKHLoMDwxSsDOL3
            DbZ58PL2iPKDrX4ep5hc7rLESwJxW/cZIkJY0VQOiCeX4pyuuYKym1YnVl8DMd2F
            RAwEchnBsquujaA+8GUgAANn1TD4gT/tpg4WtYPzVQKCAQEAlY88NwJOTbKO7VO/
            p8om3JKj5ME2nDX+NcOwR8XyHgTSXqOzh6Nm3Z7oy+oB2VWZkoNRE8NTZW2awi6X
            5sayXawfaJkwEit5xvawD+cP3dFAJcHmaWmpxVWvIm5Bll4lT/p7aEUYSp8ifOYy
            U93NRTddLVZYyqnArQ5gvHIHq8SWB8Yoxu1aijYkOtJrbAvHOqSt6vJHrJsrTB2I
            YC51ox+wv1SRtO2JhwmusiQoOOUfJbIv8dnTkCV5ce/+jfCNWVMV2GV8NNV9ckNw
            heF87wJasfqaxapKlWp1V4IpG0M3EgaOfSS9d1y4SoWC2DUKLs51EAGiDFo+FlAt
            URESEQKCAQA2CjtgHSJXGbPhCSCt6Icq47Ee4zOseUmqO7US+SX/v0virpstDK6t
            qH0UVqs/G1fypCk3zb/HTOoOTbcInWnHfs3hJMe8YQez0DRC6NdQTZwllkSeOf+p
            cpZaqsyn6XMOY+nHnE4rX558dBdqioDStp+Rz/6CPNqhZ+oJvvnbPKCKa2lx5PCC
            9RMkk9Q7cjbOUI4gReb7267ss47aJYd1B/MtVV0X/IDl2aXO6DN1CJFrBOZ7dSAu
            Q8mFCEG82OkohbeujRAagkjZEwfg86Z2hEuEDAUfPb+8hd8SRgZLUHIh91wYo4Bi
            qNmyxLqep5dkCW9jtvV8upkSHPaK3E3lAoIBAAhd0nRLPZZ+XxfFqLI3hab7nf2k
            WEkSlHucUiXaORtV2KqRz+TvxZt6saRfntWZ4Y36V5puRFbVd7QL5WYR7YuK48QT
            Qk+EbLOBic5ye/PXsl6jni9e9kYX9zmQli4xvkytq2oGwyytFq/eAeWJaiIiIZNj
            4HE+zYX+SyNHhPfvfewAVSogC4hfn823pn2UcjJOaxmZRxNHRRwICloRbYXSI35x
            44ftvDFp9NC6sNnpz7+2RNqMmGZ9EWBUk+ICURVveQMfiI2Oyqt5I+ajjSrdV+Jl
            rhaPlufjZu1UGX+0hlgVRFRYgwQnBBxosoDifV196K5xvGfYeLJzjJ5eFqw=
            -----END RSA PRIVATE KEY-----

          search-paths: '*'